"""rename image_link to image_url in User model

Revision ID: 1a8a2bec855b
Revises: ebf88715edb5
Create Date: 2025-02-23 15:19:38.524470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8a2bec855b'
down_revision: Union[str, None] = 'ebf88715edb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('users', 'image_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###
