"""added followers relationship to User model

Revision ID: 7934f5fc822e
Revises: d8f21d7a5072
Create Date: 2025-03-08 21:04:38.347083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7934f5fc822e'
down_revision: Union[str, None] = 'd8f21d7a5072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
