"""deleted backrefs for follower relationship

Revision ID: 7be6d9d533fa
Revises: 7934f5fc822e
Create Date: 2025-03-08 21:08:26.668924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be6d9d533fa'
down_revision: Union[str, None] = '7934f5fc822e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
